engines:
  pep8:
    enabled: true
  radon:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        - python
  fixme:
    enabled: true

ratings:
   paths:
   - "lazy_record/**.py"
