#!/usr/bin/env python

import os
import unittest

if __name__ == '__main__':                                                                                                                                                        
    test_dir = os.path.join(os.path.dirname(os.path.dirname(__file__)), "test")
    
    suite = unittest.TestSuite()
    tests = unittest.defaultTestLoader.discover(test_dir)
    suite.addTests(tests)
    unittest.TextTestRunner().run(suite)
